limit_per_source: 8
min_chars_to_summarize: 700

feeds:
  - name: G1
    lang: pt
    urls:
      - https://g1.globo.com/rss/g1/
  - name: CNN
    lang: en
    urls:
      - https://rss.cnn.com/rss/edition.rss
  - name: NYTimes
    lang: en
    urls:
      - https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
